const prompts = [
  {
    title: "常用",
    enable: false,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 2,
        min: 0,
        title: "优质Tag",
        list: [
          {
            value: "masterpiece, best quality",
            title: "masterpiece, best quality, 高质量",
            enable: true,
          },
          {
            value:
              "masterpiece,best quality,official art,extremely detailed CG unity 8k wallpaper",
            title:
              "masterpiece,best quality,official art,extremely detailed CG unity 8k wallpaper更高质量",
            enable: true,
          },
        ],
      },
      {
        enable: true,
        max: 2,
        min: 0,
        title: "反向Tag",
        list: [
          {
            value:
              "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, bad feet",
            title:
              "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, bad feet通用反Tag",
            enable: true,
          },
        ],
      },
    ],
  },
  {
    title: "环境",
    enable: true,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 2,
        min: 0,
        title: "朝朝暮暮",
        list: [
          { value: "day", title: "day白天", enable: true },
          { value: "dusk", title: "dusk黄昏", enable: true },
          { value: "night", title: "night夜晚", enable: true },
          { value: "in spring", title: "in spring春", enable: true },
          { value: "in summer", title: "in summer夏", enable: true },
          { value: "in autumn", title: "in autumn秋", enable: true },
          { value: "in winter", title: "in winter冬", enable: true },
        ],
      },
      {
        enable: true,
        max: 2,
        min: 0,
        title: "日月星辰",
        list: [
          { value: "sun", title: "sun太阳", enable: true },
          { value: "sunset", title: "sunset落日", enable: true },
          { value: "moon", title: "moon月亮", enable: true },
          { value: "full_moon", title: "full_moon满月", enable: true },
          { value: "stars", title: "stars星星", enable: true },
          { value: "cloudy", title: "cloudy多云", enable: true },
          { value: "rain", title: "rain下雨", enable: true },
          { value: "in the rain", title: "in the rain雨中", enable: true },
          { value: "rainy days", title: "rainy days雨天", enable: true },
        ],
      },
      {
        enable: true,
        max: 2,
        min: 0,
        title: "天涯海角",
        list: [
          { value: "sky", title: "sky天空", enable: true },
          { value: "sea", title: "sea大海", enable: true },
          { value: "mountain", title: "mountain山", enable: true },
          { value: "on a hill", title: "on a hill山上", enable: true },
          {
            value: "the top of the hill",
            title: "the top of the hill山顶",
            enable: true,
          },
          { value: "in a meadow", title: "in a meadow草地", enable: true },
          { value: "plateau", title: "plateau高原", enable: true },
          { value: "on a desert", title: "on a desert沙漠", enable: true },
          { value: "in hawaii", title: "in hawaii夏威夷", enable: true },
          { value: "cityscape", title: "cityscape城市风景", enable: true },
          { value: "landscape", title: "landscape风景", enable: true },
          {
            value: "beautiful detailed sky",
            title: "beautiful detailed sky好天",
            enable: true,
          },
          {
            value: "beautiful detailed water",
            title: "beautiful detailed water好水",
            enable: true,
          },
          { value: "on the beach", title: "on the beach海滩上", enable: true },
          {
            value: "on the ocean",
            title: "on the ocean在大海上",
            enable: true,
          },
          { value: "over the sea", title: "over the sea海边上", enable: true },
          {
            value: "beautiful purple sunset at beach",
            title: "beautiful purple sunset at beach",
            enable: true,
          },
          {
            value: "in the ocean",
            title: "in the ocean海边日落",
            enable: true,
          },
          {
            value: "against backlight at dusk",
            title: "against backlight at dusk傍晚背对阳光",
            enable: true,
          },
          {
            value: "golden hour lighting",
            title: "golden hour lighting黄金时段照明",
            enable: true,
          },
          {
            value: "strong rim light",
            title: "strong rim light强边缘光",
            enable: true,
          },
          {
            value: "intense shadows",
            title: "intense shadows强阴影",
            enable: true,
          },
          { value: "fireworks", title: "fireworks焰火", enable: true },
          { value: "flower field", title: "flower field花田", enable: true },
          { value: "underwater", title: "underwater水下", enable: true },
          { value: "explosion", title: "explosion爆炸", enable: true },
          {
            value: "in the cyberpunk city",
            title: "in the cyberpunk city在赛博朋克城市",
            enable: false,
          },
          { value: "steam", title: "steam蒸汽", enable: true },
        ],
      },
    ],
  },
  {
    title: "风格",
    enable: false,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 2,
        min: 0,
        title: "",
        list: [
          { value: "artbook", title: "artbook原画", enable: true },
          { value: "game_cg", title: "game_cg游戏CG", enable: true },
          { value: "comic", title: "comic漫画", enable: true },
          { value: "4koma", title: "4koma四格", enable: true },
          {
            value: "animated_gif",
            title: "animated_gifgif格式图片",
            enable: true,
          },
          { value: "dakimakura", title: "dakimakura抱枕", enable: true },
          { value: "cosplay", title: "cosplay角色扮演", enable: true },
          { value: "crossover", title: "crossover穿越", enable: true },
          { value: "dark", title: "dark暗的", enable: true },
          { value: "light", title: "light亮的", enable: true },
          { value: "night", title: "night晚上", enable: true },
          { value: "guro", title: "guro猎奇", enable: false },
          { value: "realistic", title: "realistic写实", enable: true },
          { value: "photo", title: "photo照片", enable: true },
          { value: "real", title: "real真实", enable: true },
          {
            value: "landscape/scenery",
            title: "landscape/scenery风景",
            enable: true,
          },
          { value: "cityscape", title: "cityscape城市风景", enable: true },
          {
            value: "science_fiction",
            title: "science_fiction科技幻想",
            enable: true,
          },
          { value: "original", title: "original原创", enable: true },
          { value: "parody", title: "parody拙劣的模仿", enable: true },
          {
            value: "personification",
            title: "personification拟人",
            enable: true,
          },
          { value: "checkered", title: "checkered格子的", enable: true },
          { value: "lowres", title: "lowres低分辨率", enable: true },
          { value: "highres", title: "highres高分辨率", enable: true },
          { value: "absurdres", title: "absurdres超高分辨率", enable: true },
          {
            value: "incredibly_absurdres",
            title: "incredibly_absurdres极高分辨率",
            enable: true,
          },
          {
            value: "huge_filesize",
            title: "huge_filesize超级高分辨率/大文件",
            enable: true,
          },
          { value: "wallpaper", title: "wallpaper壁纸", enable: true },
          { value: "pixel_art", title: "pixel_art点阵图", enable: true },
          { value: "monochrome", title: "monochrome单色图片", enable: true },
          { value: "colorful", title: "colorful色彩斑斓的", enable: true },
          {
            value: "optical_illusion",
            title: "optical_illusion视觉错误",
            enable: true,
          },
          {
            value: "fine_art_parody",
            title: "fine_art_parody名画模仿",
            enable: true,
          },
          { value: "sketch", title: "sketch素描", enable: true },
          {
            value: "traditional_media",
            title: "traditional_media传统媒体（基本上是手绘稿）",
            enable: true,
          },
          {
            value: "watercolor_(medium)",
            title: "watercolor_(medium)透明水彩绘",
            enable: true,
          },
          { value: "silhouette", title: "silhouette剪影", enable: true },
          { value: "covr", title: "covr封面", enable: true },
          { value: "album", title: "album专辑", enable: true },
          { value: "sample", title: "sample图上有sample字样", enable: true },
          { value: "back", title: "back背影像", enable: true },
          { value: "bust", title: "bust半身像", enable: true },
          { value: "profile", title: "profile侧面绘", enable: true },
          {
            value: "expressions",
            title: "expressions表情绘（各种表情）",
            enable: true,
          },
          {
            value: "everyone",
            title: "everyone一部作品中的主要人物集齐",
            enable: true,
          },
          {
            value: "column_lineup",
            title: "column_lineup一列列小图组成大图",
            enable: true,
          },
          {
            value: "transparent_background",
            title: "transparent_background透明的背景(.png)",
            enable: true,
          },
          {
            value: "simple_background",
            title: "simple_background简单的背景(无背景)",
            enable: true,
          },
          {
            value: "gradient_background",
            title: "gradient_background渐变的背景",
            enable: true,
          },
          {
            value: "zoom_layer",
            title: "zoom_layer背景是前景的放大版",
            enable: true,
          },
          { value: "English", title: "English英文", enable: true },
          { value: "Chinese", title: "Chinese中文", enable: true },
          { value: "French", title: "French法文", enable: true },
          { value: "Japanese", title: "Japanese日本人", enable: true },
          {
            value: "translation_request",
            title: "translation_request翻译",
            enable: true,
          },
          {
            value: "bad_id",
            title: "bad_idID转向错误(原地址或已被删除)",
            enable: true,
          },
          {
            value: "tagme",
            title: "tagme图片有一些上传者未知的项目",
            enable: true,
          },
          {
            value: "artist_request",
            title: "artist_request作者未知,需要补完",
            enable: true,
          },
          { value: "what", title: "what不知所谓", enable: true },
        ],
      },
    ],
  },
  {
    title: "人物",
    enable: true,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 2,
        min: 0,
        title: "",
        list: [
          { value: "girl", title: "girl女孩", enable: true },
          { value: "2girls", title: "2girls2女孩", enable: false },
          { value: "3girls", title: "3girls3女孩", enable: false },
          { value: "boy", title: "boy男孩", enable: false },
          { value: "2boys", title: "2boys2男孩", enable: false },
          { value: "3boys", title: "3boys3男孩", enable: false },
          { value: "solo", title: "solo单人", enable: true },
          {
            value: "multiple girls",
            title: "multiple girls多个",
            enable: false,
          },
          { value: "little girl", title: "little girl小女孩", enable: true },
          { value: "little boy", title: "little boy小男孩", enable: false },
          { value: "shota", title: "shota正太", enable: false },
          { value: "loli", title: "loli萝莉", enable: true },
          { value: "kawaii", title: "kawaii可爱", enable: true },
          { value: "mesugaki", title: "mesugaki雌小鬼", enable: false },
          {
            value: "adorable girl",
            title: "adorable girl可爱的女孩",
            enable: true,
          },
          { value: "bishoujo", title: "bishoujo美少女", enable: true },
          { value: "gyaru", title: "gyaru辣妹", enable: true },
          { value: "sisters", title: "sisters姐妹", enable: false },
          { value: "ojousama", title: "ojousama大小姐", enable: true },
          {
            value: "mature female",
            title: "mature female成熟女性",
            enable: true,
          },
          { value: "mature", title: "mature成熟", enable: true },
          {
            value: "female pervert",
            title: "female pervert痴女",
            enable: true,
          },
          { value: "milf", title: "milf熟女", enable: true },
          { value: "harem", title: "harem后宫", enable: true },
        ],
      },
    ],
  },
  {
    title: "角色",
    enable: true,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 2,
        min: 0,
        title: "",
        list: [
          { value: "angel", title: "angel天使", enable: true },
          { value: "cheerleader", title: "cheerleader啦啦队", enable: true },
          { value: "chibi", title: "chibiQ版人物", enable: true },
          { value: "crossdressing", title: "crossdressing伪娘", enable: false },
          { value: "devil", title: "devil魔鬼", enable: true },
          { value: "doll", title: "doll人偶", enable: true },
          { value: "elf", title: "elf妖精", enable: true },
          { value: "fairy", title: "fairy小精灵", enable: true },
          { value: "female", title: "female女人", enable: true },
          { value: "furry", title: "furry兽人", enable: true },
          { value: "orc", title: "orc半兽人", enable: true },
          { value: "giantess", title: "giantess女巨人", enable: false },
          { value: "harem", title: "harem后宫", enable: true },
          { value: "idol", title: "idol偶像", enable: true },
          {
            value: "kemonomimi_mode",
            title: "kemonomimi_mode兽耳萝莉模式",
            enable: true,
          },
          { value: "loli", title: "loli萝莉", enable: true },
          {
            value: "magical_girl",
            title: "magical_girl魔法少女",
            enable: true,
          },
          { value: "maid", title: "maid女仆", enable: true },
          { value: "male", title: "male男人", enable: false },
          { value: "mermaid", title: "mermaid美人鱼", enable: true },
          { value: "miko", title: "miko巫女", enable: true },
          { value: "milf", title: "milf熟女", enable: true },
          { value: "minigirl", title: "minigirl迷你女孩", enable: false },
          { value: "monster", title: "monster怪物", enable: true },
          {
            value: "multiple_girls",
            title: "multiple_girls魔幻少女",
            enable: true,
          },
          { value: "ninja", title: "ninja忍者", enable: true },
          { value: "no_humans", title: "no_humans非人", enable: false },
          { value: "nun", title: "nun修女", enable: true },
          { value: "nurse", title: "nurse护士", enable: true },
          { value: "shota", title: "shota正太", enable: true },
          { value: "stewardess", title: "stewardess空姐", enable: true },
          { value: "student", title: "student学生", enable: true },
          { value: "trap", title: "trap伪娘", enable: false },
          { value: "vampire", title: "vampire吸血鬼", enable: true },
          { value: "waitress", title: "waitress女服务员", enable: true },
          { value: "witch", title: "witch女巫", enable: true },
          { value: "yaoi", title: "yaoi搞基", enable: false },
          {
            value: "yukkuri_shiteitte_ne",
            title: "yukkuri_shiteitte_ne油库里",
            enable: false,
          },
          { value: "yuri", title: "yuri百合", enable: true },
        ],
      },
    ],
  },
  {
    title: "头发",
    enable: true,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 2,
        min: 0,
        title: "发色",
        list: [
          { value: "white hair", title: "white hair白", enable: true },
          { value: "blonde hair", title: "blonde hair 金", enable: true },
          { value: "silver hair", title: "silver hair银", enable: true },
          { value: "grey hair", title: "grey hair 灰", enable: true },
          { value: "purple hair", title: "purple hair紫", enable: true },
          { value: "red hair", title: "red hair红", enable: true },
          { value: "yellow hair", title: "yellow hair黄", enable: true },
          { value: "green hair", title: "green hair绿", enable: true },
          { value: "blue hair", title: "blue hair蓝", enable: true },
          { value: "black hair", title: "black hair黑", enable: true },
          { value: "brown hair", title: "brown hair棕", enable: true },
          { value: "streaked hair", title: "streaked hair挑染", enable: true },
          {
            value: "grey gradient hair",
            title: "grey gradient hair灰色渐变",
            enable: true,
          },
          {
            value: "light brown hair",
            title: "light brown hair亮棕",
            enable: true,
          },
          { value: "two-tone hair", title: "two-tone hair双色", enable: true },
          {
            value: "multicolored hair",
            title: "multicolored hair五颜六色",
            enable: true,
          },
        ],
      },
      {
        enable: true,
        max: 2,
        min: 0,
        title: "辫子",
        list: [
          {
            value: "high ponytail",
            title: "high ponytail高马尾",
            enable: true,
          },
          { value: "twintails", title: "twintails双马尾", enable: true },
          { value: "braid", title: "braid马尾编发", enable: true },
          {
            value: "braided ponytail",
            title: "braided ponytail 马尾编发",
            enable: true,
          },
          { value: "ponytail", title: "ponytail马尾辫", enable: true },
          {
            value: "short_ponytail",
            title: "short_ponytail短马尾",
            enable: true,
          },
          { value: "twin_braids", title: "twin_braids双辫子", enable: true },
        ],
      },
      {
        enable: true,
        max: 1,
        min: 1,
        title: "头发长度",
        list: [
          { value: "short hair", title: "short hair短发", enable: true },
          { value: "medium hair", title: "medium hair中发", enable: true },
          { value: "long hair", title: "long hair长发", enable: true },
          {
            value: "very long hair",
            title: "very long hair超长发",
            enable: true,
          },
        ],
      },
      {
        enable: true,
        max: 2,
        min: 0,
        title: "头发类型",
        list: [
          {
            value: "braided bangs",
            title: "braided bangs辫子刘海",
            enable: true,
          },
          { value: "swept bangs", title: "swept bangs侧扫刘海", enable: true },
          {
            value: "hair between eyes",
            title: "hair between eyes眼间头发",
            enable: true,
          },
          { value: "bob cut", title: "bob cut妹妹切", enable: true },
          { value: "hime_cut", title: "hime_cut公主切", enable: true },
          {
            value: "crossed bangs",
            title: "crossed bangs交叉刘海",
            enable: true,
          },
          { value: "bangs", title: "bangs刘海", enable: true },
          { value: "blunt bangs", title: "blunt bangs齐刘海", enable: true },
          { value: "hair wings", title: "hair wings翼状头发", enable: true },
          { value: "long bangs", title: "long bangs长刘海", enable: true },
          {
            value: "disheveled hair",
            title: "disheveled hair蓬发",
            enable: true,
          },
          { value: "wavy hair", title: "wavy hair波浪形头发", enable: true },
          { value: "curly_hair", title: "curly_hair卷发", enable: true },
          { value: "hair in takes", title: "hair in takes收拢", enable: true },
          { value: "scrunchie", title: "scrunchie发带", enable: true },
          {
            value: "hair pink flowers",
            title: "hair pink flowers粉色花",
            enable: true,
          },
          { value: "ahoge", title: "ahoge呆毛", enable: true },
          {
            value: "antenna hair",
            title: "antenna hair多根呆毛",
            enable: true,
          },
          {
            value: "Side ponytail",
            title: "Side ponytail侧马尾",
            enable: true,
          },
          { value: "forehead", title: "forehead露额头", enable: true },
          {
            value: "drill hair",
            title: "drill hair钻头卷/公主卷",
            enable: true,
          },
          { value: "hair bun", title: "hair bun包子头", enable: true },
          { value: "double_bun", title: "double_bun俩包子头", enable: true },
          { value: "messy_hair", title: "messy_hair凌乱发型", enable: true },
        ],
      },
    ],
  },
  {
    title: "五官",
    enable: true,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 1,
        min: 0,
        title: "",
        list: [
          { value: "light smile", title: "light smile微笑", enable: true },
          {
            value: "seductive smile",
            title: "seductive smile诱惑笑",
            enable: true,
          },
          { value: "grin", title: "grin露齿而笑", enable: true },
          { value: "laughing", title: "laughing笑", enable: true },
          { value: "teeth", title: "teeth 牙", enable: true },
          { value: "excited", title: "excited兴奋", enable: true },
          { value: "embarrassed", title: "embarrassed 害羞", enable: true },
          { value: "blush", title: "blush脸红", enable: true },
          { value: "shy", title: "shy害羞", enable: true },
          { value: "nose blush", title: "nose blush 害羞", enable: true },
          {
            value: "expressionless",
            title: "expressionless无表情",
            enable: true,
          },
          {
            value: "expressionless eyes",
            title: "expressionless eyes失神",
            enable: true,
          },
          { value: "sleepy", title: "sleepy困", enable: true },
          { value: "drunk", title: "drunk喝醉的", enable: true },
          { value: "tears", title: "tears哭", enable: true },
          {
            value: "crying with eyes open",
            title: "crying with eyes open哭",
            enable: true,
          },
          { value: "sad", title: "sad悲伤的", enable: true },
          { value: "pout", title: "pout别扭 努嘴", enable: true },
          { value: "sigh", title: "sigh叹气", enable: true },
          { value: "wide eyed", title: "wide eyed睁大眼睛", enable: true },
          { value: "angry", title: "angry生气", enable: true },
          { value: "annoyed", title: "annoyed苦恼的", enable: true },
          { value: "frown", title: "frown皱眉", enable: true },
          { value: "smirk", title: "smirk认真", enable: true },
          { value: "serious", title: "serious严肃", enable: true },
          { value: "jitome", title: "jitome鄙夷", enable: true },
          { value: "scowl", title: "scowl锐利", enable: true },
          { value: "crazy", title: "crazy疯狂的", enable: true },
          { value: "dark_persona", title: "dark_persona黑化的", enable: true },
          { value: "smirk", title: "smirk微笑", enable: true },
          { value: "smug", title: "smug得意", enable: true },
          { value: "naughty_face", title: "naughty_face调皮脸", enable: true },
          {
            value: "one eye closed",
            title: "one eye closed一只眼睛闭上",
            enable: true,
          },
          {
            value: "half-closed eyes",
            title: "half-closed eyes半闭眼睛",
            enable: true,
          },
          { value: "nosebleed", title: "nosebleed鼻血", enable: true },
          { value: "eyelid pull", title: "eyelid pull 做鬼脸", enable: true },
          { value: "tongue", title: "tongue舌头", enable: true },
          { value: "tongue out", title: "tongue out吐舌", enable: true },
          { value: "closed mouth", title: "closed mouth闭嘴", enable: true },
          { value: "open mouth", title: "open mouth张嘴", enable: true },
          { value: "lipstick", title: "lipstick口红", enable: true },
          { value: "fangs", title: "fangs尖牙", enable: true },
          {
            value: "clenched teeth",
            title: "clenched teeth咬紧牙关",
            enable: true,
          },
          { value: ":3", title: ":3ω猫嘴", enable: true },
          { value: ":p", title: ":p向下吐舌头", enable: true },
          { value: ":q", title: ":q向上吐舌头", enable: true },
          { value: ":t", title: ":t不耐烦", enable: true },
          { value: ":d", title: ":d杯型笑脸", enable: true },
        ],
      },
      {
        enable: true,
        max: 1,
        min: 0,
        title: "",
        list: [
          {
            value: "naughty_face",
            title: "naughty_face下流的表情",
            enable: true,
          },
          {
            value: "endured_face",
            title: "endured_face忍耐的表情",
            enable: true,
          },
          { value: "ahegao", title: "ahegao阿黑颜", enable: true },
          {
            value: "blood on face",
            title: "blood on face血在脸上",
            enable: true,
          },
          { value: "saliva", title: "saliva唾液", enable: true },
        ],
      },
    ],
  },
  {
    title: "表情",
    enable: true,
    max: 1,
    min: 0,
    list: [
      {
        enable: true,
        max: 2,
        min: 0,
        title: "",
        list: [
          {
            value: "food on face",
            title: "food on face 食物在脸上（食物可替换）",
            enable: true,
          },
          { value: "light blush", title: "light blush淡淡腮红", enable: true },
          { value: "facepaint", title: "facepaint面纹", enable: false },
          { value: "makeup", title: "makeup 浓妆", enable: true },
          { value: "cute face", title: "cute face可爱表情", enable: true },
          {
            value: "white colored eyelashes",
            title: "white colored eyelashes白色睫毛",
            enable: true,
          },
          {
            value: "longeyelashes",
            title: "longeyelashes长睫毛",
            enable: true,
          },
          {
            value: "white eyebrows",
            title: "white eyebrows白色眉毛",
            enable: true,
          },
          { value: "tsurime", title: "tsurime吊眼角", enable: true },
          {
            value: "gradient_eyes",
            title: "gradient_eyes渐变眼",
            enable: true,
          },
          {
            value: "beautiful detailed eyes",
            title: "beautiful detailed eyes美丽的细节眼睛",
            enable: true,
          },
          { value: "tareme", title: "tareme垂眼角", enable: true },
          { value: "slit pupils", title: "slit pupils 猫眼", enable: true },
          {
            value: "heterochromia",
            title: "heterochromia 异色瞳",
            enable: true,
          },
          {
            value: "heterochromia blue red",
            title: "heterochromia blue red红蓝眼",
            enable: true,
          },
          { value: "aqua eyes", title: "aqua eyes水汪汪大眼", enable: true },
          {
            value: "looking at viewer",
            title: "looking at viewer看你",
            enable: true,
          },
          { value: "eyeball", title: "eyeball盯着看", enable: true },
          { value: "stare", title: "stare凝视", enable: true },
          {
            value: "visible through hair",
            title: "visible through hair透过刘海看",
            enable: true,
          },
          {
            value: "looking to the side",
            title: "looking to the side 看旁边",
            enable: true,
          },
          {
            value: "constricted pupils",
            title: "constricted pupils收缩的瞳孔",
            enable: true,
          },
          {
            value: "symbol-shaped pupils",
            title: "symbol-shaped pupils 符号形状的瞳孔",
            enable: true,
          },
          { value: "heart in eye", title: "heart in eye❤", enable: true },
          {
            value: "heart-shaped pupils",
            title: "heart-shaped pupils爱心瞳孔",
            enable: true,
          },
          { value: "wink", title: "wink 眨眼", enable: true },
          {
            value: "mole under eye",
            title: "mole under eye眼下痣",
            enable: true,
          },
          { value: "eyes closed", title: "eyes closed 闭眼", enable: true },
          { value: "no_nose", title: "no_nose没鼻子", enable: false },
          {
            value: "fake animal ears",
            title: "fake animal ears动物耳朵",
            enable: true,
          },
          {
            value: "animal ear fluff",
            title: "animal ear fluff 动物耳绒毛",
            enable: true,
          },
          { value: "animal_ears", title: "animal_ears动物耳朵", enable: true },
          { value: "fox_ears", title: "fox_ears狐狸耳朵", enable: true },
          { value: "bunny_ears", title: "bunny_ears兔子耳朵", enable: true },
          { value: "cat_ears", title: "cat_ears猫耳", enable: true },
          { value: "dog_ears", title: "dog_ears狗耳", enable: true },
          { value: "mouse_ears", title: "mouse_ears叔耳", enable: true },
          { value: "hair ear", title: "hair ear 头发上耳朵", enable: true },
          { value: "pointy ears", title: "pointy ears 尖耳", enable: true },
        ],
      },
    ],
  },
  {
    title: "动作",
    enable: true,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 1,
        min: 0,
        title: "",
        list: [
          { value: "head tilt", title: "head tilt 歪头", enable: true },
          {
            value: "turning around",
            title: "turning around回头",
            enable: true,
          },
          { value: "looking back", title: "looking back回头", enable: true },
          { value: "looking down", title: "looking down向下看", enable: true },
          { value: "looking up", title: "looking up向上看", enable: true },
          { value: "smelling", title: "smelling闻", enable: true },
          {
            value: "hand_to_mouth",
            title: "hand_to_mouth手放在嘴边",
            enable: true,
          },
          {
            value: "arm at side",
            title: "arm at side 手放头旁边",
            enable: true,
          },
          {
            value: "arms behind head",
            title: "arms behind head手放脑后",
            enable: true,
          },
          {
            value: "arms behind back",
            title: "arms behind back 手放后面",
            enable: true,
          },
          {
            value: "hand on own chest",
            title: "hand on own chest手放在自己的胸前",
            enable: true,
          },
          {
            value: "arms_crossed",
            title: "arms_crossed手交叉于胸前",
            enable: true,
          },
          { value: "hand on hip", title: "hand on hip 手放臀", enable: true },
          {
            value: "hand on another's hip",
            title: "hand on another's hip 手放臀",
            enable: true,
          },
          { value: "hand_on_hip", title: "hand_on_hip单手插腰", enable: true },
          {
            value: "hands_on_hips",
            title: "hands_on_hips双手叉腰",
            enable: true,
          },
          { value: "arms up", title: "arms up举手", enable: true },
          { value: "hands up", title: "hands up 举手", enable: true },
          { value: "stretch", title: "stretch伸懒腰", enable: true },
          { value: "armpits", title: "armpits举手露腋", enable: true },
          { value: "leg hold", title: "leg hold手把腿抓着", enable: true },
          { value: "grabbing", title: "grabbing抓住", enable: true },
          { value: "holding", title: "holding拿着", enable: true },
          {
            value: "fingersmile",
            title: "fingersmile用手指做出笑脸",
            enable: true,
          },
          { value: "hair_pull", title: "hair_pull拉头发", enable: true },
          {
            value: "hair scrunchie",
            title: "hair scrunchie撮头发",
            enable: true,
          },
          { value: "w", title: "w 手势", enable: true },
          { value: "v", title: "v耶", enable: true },
          { value: "peace symbol", title: "peace symbol 耶", enable: true },
          { value: "thumbs_up", title: "thumbs_up翘大拇指", enable: true },
          {
            value: "middle_finger",
            title: "middle_finger比出中指",
            enable: true,
          },
          { value: "cat_pose", title: "cat_pose猫爪手势", enable: true },
          { value: "finger_gun", title: "finger_gun手枪手势", enable: true },
          { value: "shushing", title: "shushing嘘手势", enable: true },
          { value: "waving", title: "waving招手", enable: true },
          { value: "salute", title: "salute敬礼", enable: true },
          { value: "spread_arms", title: "spread_arms张手", enable: true },
          { value: "spread legs", title: "spread legs张开腿", enable: true },
          { value: "crossed_legs", title: "crossed_legs二郎腿", enable: true },
          {
            value: "fetal_position",
            title: "fetal_position曲腿至胸",
            enable: true,
          },
          { value: "leg_lift", title: "leg_lift抬一只脚", enable: true },
          { value: "legs_up", title: "legs_up抬两只脚", enable: true },
          {
            value: "leaning forward",
            title: "leaning forward 前倾",
            enable: true,
          },
          {
            value: "fetal position",
            title: "fetal position婴儿姿势",
            enable: true,
          },
          { value: "against wall", title: "against wall靠墙", enable: true },
          { value: "on_stomach", title: "on_stomach趴着", enable: true },
          { value: "squatting", title: "squatting蹲下", enable: true },
          { value: "lying", title: "lying 躺着", enable: true },
          { value: "sitting", title: "sitting 坐", enable: true },
          { value: "sitting on", title: "sitting on 坐", enable: true },
          { value: "seiza", title: "seiza正坐", enable: true },
          {
            value: "wariza/w-sitting",
            title: "wariza/w-sitting割坐",
            enable: true,
          },
          { value: "yokozuwari", title: "yokozuwari侧身坐", enable: true },
          { value: "indian_style", title: "indian_style盘腿", enable: true },
          { value: "leg_hug", title: "leg_hug抱腿", enable: true },
          { value: "walking", title: "walking走", enable: true },
          { value: "running", title: "running跑", enable: true },
          { value: "straddle", title: "straddle跨坐", enable: true },
          { value: "straddling", title: "straddling跨坐", enable: true },
          { value: "kneeling", title: "kneeling下跪", enable: true },
          { value: "smoking", title: "smoking抽烟", enable: true },
          {
            value: "arm_support",
            title: "arm_support用手支撑住",
            enable: true,
          },
          {
            value: "caramelldansen",
            title: "caramelldansenniconiconi",
            enable: true,
          },
          {
            value: "princess_carry",
            title: "princess_carry公主抱",
            enable: true,
          },
          {
            value: "fighting_stance",
            title: "fighting_stance战斗姿态",
            enable: true,
          },
          { value: "upside-down", title: "upside-down颠倒的", enable: true },
          {
            value: "top-down_bottom-up",
            title: "top-down_bottom-up趴着翘臀",
            enable: true,
          },
          { value: "bent_over", title: "bent_over翘臀姿势", enable: true },
          { value: "arched_back", title: "arched_back弓身体", enable: true },
          { value: "back-to-back", title: "back-to-back背对背", enable: true },
          {
            value: "symmetrical_hand_pose",
            title: "symmetrical_hand_pose手对手",
            enable: true,
          },
          {
            value: "eye_contact",
            title: "eye_contact眼对眼（对视）",
            enable: true,
          },
          { value: "hug", title: "hug拥抱", enable: true },
          { value: "lap_pillow", title: "lap_pillow膝枕", enable: true },
          { value: "sleeping", title: "sleeping睡觉", enable: true },
          { value: "bathing", title: "bathing洗澡", enable: true },
          { value: "mimikaki", title: "mimikaki掏耳勺", enable: true },
          { value: "holding_hands", title: "holding_hands牵手", enable: true },
        ],
      },
      {
        enable: false,
        max: 2,
        min: 0,
        title: "",
        list: [
          { value: "all_fours", title: "all_fours四肢趴地", enable: true },
          {
            value: "symmetrical_docking",
            title: "symmetrical_docking2女胸部贴在一起",
            enable: false,
          },
          { value: "undressing", title: "undressing脱衣服", enable: true },
          { value: "skirt lift", title: "skirt lift掀起裙子", enable: true },
          { value: "shirt lift", title: "shirt lift掀起上衣", enable: true },
          {
            value: "adjusting_thighhigh",
            title: "adjusting_thighhigh调整过膝袜",
            enable: true,
          },
        ],
      },
    ],
  },
  {
    title: "服装",
    enable: true,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 1,
        min: 0,
        title: "",
        list: [
          { value: "sailor collar", title: "sailor collar领子", enable: true },
          { value: "hat", title: "hat帽子", enable: true },
          { value: "shirt", title: "shirt衬衫", enable: true },
          { value: "serafuku", title: "serafuku水手服", enable: true },
          { value: "sailor suite", title: "sailor suite水手服", enable: true },
          { value: "sailor shirt", title: "sailor shirt水手服", enable: true },
          {
            value: "shorts under skirt",
            title: "shorts under skirt水手服",
            enable: true,
          },
          {
            value: "collared shirt",
            title: "collared shirt 有领衬衣",
            enable: true,
          },
          {
            value: "school uniform",
            title: "school uniform学校制服",
            enable: true,
          },
          { value: "seifuku", title: "seifuku日本学生服", enable: true },
          {
            value: "business_suit",
            title: "business_suit职场制服",
            enable: true,
          },
          { value: "jacket", title: "jacket夹克", enable: true },
          { value: "suit", title: "suit 西装", enable: true },
          {
            value: "garreg mach monastery uniform",
            title: "garreg mach monastery uniform火焰纹章军服",
            enable: true,
          },
          {
            value: "revealing dress",
            title: "revealing dress礼服长裙",
            enable: true,
          },
          {
            value: "pink lucency full dress",
            title: "pink lucency full dress礼服",
            enable: true,
          },
          {
            value: "cleavage dress",
            title: "cleavage dress露出胸口部分的连衣裙",
            enable: true,
          },
          {
            value: "sleeveless dress",
            title: "sleeveless dress无袖连衣裙",
            enable: true,
          },
          { value: "whitedress", title: "whitedress白色连衣裙", enable: true },
          { value: "wedding_dress", title: "wedding_dress婚纱", enable: true },
          {
            value: "Sailor dress",
            title: "Sailor dress水手连衣裙",
            enable: true,
          },
          {
            value: "sweater dress",
            title: "sweater dress毛衣裙",
            enable: true,
          },
          {
            value: "ribbed sweater",
            title: "ribbed sweater罗纹毛衣",
            enable: true,
          },
          {
            value: "sweater jacket",
            title: "sweater jacket毛衣夹克",
            enable: true,
          },
          { value: "dungarees", title: "dungarees工装服", enable: true },
          {
            value: "brown cardigan",
            title: "brown cardigan 棕色开襟衫（外套）",
            enable: true,
          },
          { value: "hoodie", title: "hoodie 连帽衫，卫衣", enable: true },
          { value: "robe", title: "robe长袍", enable: true },
          { value: "cape", title: "cape斗篷", enable: true },
          { value: "cardigan", title: "cardigan羊毛衫", enable: true },
          { value: "apron", title: "apron围裙", enable: true },
          { value: "gothic", title: "gothic哥特风格", enable: true },
          {
            value: "lolita_fashion",
            title: "lolita_fashion洛丽塔风格",
            enable: true,
          },
          {
            value: "gothic_lolita",
            title: "gothic_lolita哥特洛丽塔风格",
            enable: true,
          },
          { value: "western", title: "western西部风格", enable: true },
          { value: "tartan", title: "tartan格子花纹", enable: true },
          { value: "off_shoulder", title: "off_shoulder露单肩", enable: true },
          {
            value: "bare_shoulders",
            title: "bare_shoulders露双肩",
            enable: true,
          },
          { value: "barefoot", title: "barefoot赤脚", enable: true },
          { value: "bare_legs", title: "bare_legs裸足", enable: true },
          { value: "striped", title: "striped横条花纹的", enable: true },
          { value: "polka_dot", title: "polka_dot点状花纹的", enable: true },
          { value: "frills", title: "frills皱边的", enable: true },
          { value: "lace", title: "lace花边", enable: true },
          { value: "buruma", title: "buruma日本女生运动短裤", enable: true },
          { value: "sportswear", title: "sportswear运动服", enable: true },
          { value: "gym_uniform", title: "gym_uniform运动服", enable: true },
          { value: "tank_top", title: "tank_top女用背心", enable: true },
          {
            value: "cropped jacket",
            title: "cropped jacket 裁剪短夹克",
            enable: true,
          },
          {
            value: "black sports bra",
            title: "black sports bra 运动胸罩",
            enable: true,
          },
          { value: "crop top", title: "crop top漏脐装", enable: true },
          { value: "pajamas", title: "pajamas睡衣", enable: true },
          {
            value: "japanese_clothes",
            title: "japanese_clothes和服",
            enable: true,
          },
          { value: "obi", title: "obi衣带(和服用)", enable: true },
          { value: "mesh", title: "mesh网眼上衣", enable: true },
          {
            value: "sleeveless shirt",
            title: "sleeveless shirt无袖上衣",
            enable: true,
          },
          {
            value: "detached_sleeves",
            title: "detached_sleeves袖肩分离装",
            enable: true,
          },
          {
            value: "white bloomers",
            title: "white bloomers白色灯笼裤",
            enable: true,
          },
          {
            value: "high - waist shorts",
            title: "high - waist shorts 高腰腿裤",
            enable: true,
          },
          {
            value: "pleated_skirt",
            title: "pleated_skirt百褶裙",
            enable: true,
          },
          { value: "skirt", title: "skirt裙子", enable: true },
          { value: "miniskirt", title: "miniskirt迷你裙", enable: true },
          { value: "short shorts", title: "short shorts热裤", enable: true },
          {
            value: "summer_dress",
            title: "summer_dress夏日长裙",
            enable: true,
          },
          { value: "bloomers", title: "bloomers灯笼裤", enable: true },
          { value: "shorts", title: "shorts短裤", enable: true },
          {
            value: "bike_shorts",
            title: "bike_shorts自行车短裤",
            enable: true,
          },
          {
            value: "dolphin shorts",
            title: "dolphin shorts海豚短裤",
            enable: true,
          },
          { value: "belt", title: "belt腰带", enable: true },
          { value: "bikini", title: "bikini比基尼（前加颜色）", enable: true },
          {
            value: "sling bikini",
            title: "sling bikini吊索比基尼",
            enable: true,
          },
          { value: "bikini_top", title: "bikini_top比基尼乳罩", enable: true },
          {
            value: "bikini top only",
            title: "bikini top only 上身比基尼",
            enable: true,
          },
          {
            value: "side - tie bikini bottom",
            title: "side - tie bikini bottom侧边系带比基尼下装",
            enable: true,
          },
          {
            value: "side-tie_bikini",
            title: "side-tie_bikini系带式比基尼",
            enable: true,
          },
          {
            value: "friled bikini",
            title: "friled bikini褶边比基尼",
            enable: true,
          },
          {
            value: "bikini under clothes",
            title: "bikini under clothes比基尼内衣",
            enable: true,
          },
          { value: "swimsuit", title: "swimsuit泳装", enable: true },
          {
            value: "school swimsuit",
            title: "school swimsuit学校泳衣",
            enable: true,
          },
          {
            value: "one-piece swimsuit",
            title: "one-piece swimsuit连体泳衣",
            enable: true,
          },
          {
            value: "competition swimsuit",
            title: "competition swimsuit竞技泳衣",
            enable: true,
          },
          { value: "Sukumizu", title: "Sukumizu死库水", enable: true },
        ],
      },
      {
        enable: true,
        max: 2,
        min: 0,
        title: "",
        list: [
          { value: "no bra", title: "no bra没胸罩", enable: true },
          { value: "bra", title: "bra 胸罩", enable: true },
          { value: "victorian", title: "victorian褶边文胸", enable: true },
          { value: "frilled bra", title: "frilled bra 褶边文胸", enable: true },
          {
            value: "sexy lingerie",
            title: "sexy lingerie情趣内衣",
            enable: true,
          },
          {
            value: "transparent underwear",
            title: "transparent underwear透明内衣",
            enable: true,
          },
          { value: "sarashi", title: "sarashi缠胸布", enable: true },
          { value: "bustier", title: "bustier胸衣", enable: true },
          { value: "chemise", title: "chemise吊带胸衣", enable: true },
          { value: "underwear", title: "underwear内衣", enable: true },
          { value: "panties", title: "panties内裤（前加颜色）", enable: true },
          {
            value: "striped_panties",
            title: "striped_panties条纹内裤",
            enable: true,
          },
          { value: "no_panties", title: "no_panties没内裤", enable: true },
          {
            value: "lowleg_panties/low_leg_panties",
            title: "lowleg_panties/low_leg_panties低腰式内裤",
            enable: true,
          },
          {
            value: "side-tie_panties",
            title: "side-tie_panties侧系带内裤",
            enable: true,
          },
          {
            value: "string_panties",
            title: "string_panties高腰内裤",
            enable: true,
          },
          { value: "thong", title: "thong丁字裤", enable: true },
          { value: "fundoshi", title: "fundoshi日式丁字裤", enable: true },
          { value: "lingerie", title: "lingerie女用贴身内衣裤", enable: true },
        ],
      },
    ],
  },
  {
    title: "鞋袜",
    enable: true,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 1,
        min: 0,
        title: "",
        list: [
          { value: "shoes", title: "shoes 鞋子", enable: true },
          { value: "boots", title: "boots靴子", enable: true },
          { value: "loafers", title: "loafers乐福鞋", enable: true },
          { value: "high heels", title: "high heels高跟鞋", enable: true },
          {
            value: "cross-laced_footwear",
            title: "cross-laced_footwear系带靴",
            enable: true,
          },
          { value: "mary_janes", title: "mary_janes玛丽珍鞋", enable: true },
          { value: "uwabaki", title: "uwabaki女式学生鞋", enable: true },
          { value: "slippers", title: "slippers拖鞋", enable: true },
          { value: "knee_boots", title: "knee_boots马靴", enable: true },
        ],
      },
      {
        enable: true,
        max: 1,
        min: 0,
        title: "",
        list: [
          { value: "pantyhose", title: "pantyhose 连裤袜", enable: true },
          {
            value: "thighband pantyhose",
            title: "thighband pantyhose 大腿连裤袜",
            enable: true,
          },
          {
            value: "garter_belt",
            title: "garter_belt连腰吊带袜",
            enable: true,
          },
          {
            value: "garter straps",
            title: "garter straps吊带袜",
            enable: true,
          },
          { value: "socks", title: "socks短袜", enable: true },
          {
            value: "striped_socks",
            title: "striped_socks横条袜",
            enable: true,
          },
          { value: "loose_socks", title: "loose_socks泡泡袜", enable: true },
          { value: "legwear", title: "legwear裹腿", enable: true },
          {
            value: "black leggings",
            title: "black leggings 黑色紧身裤",
            enable: true,
          },
          { value: "leggings", title: "leggings 裤袜", enable: true },
          { value: "fishnets", title: "fishnets网袜", enable: true },
          {
            value: "fishnet_stockings",
            title: "fishnet_stockings渔网袜",
            enable: true,
          },
          {
            value: "fishnet_pantyhose",
            title: "fishnet_pantyhose渔网袜",
            enable: true,
          },
          { value: "kneehighs", title: "kneehighs长袜", enable: true },
          { value: "stockings", title: "stockings丝袜", enable: true },
          { value: "thighhighs", title: "thighhighs过膝袜", enable: true },
          {
            value: "striped_thighhighs",
            title: "striped_thighhighs条纹过膝袜",
            enable: true,
          },
          {
            value: "white_thighhighs",
            title: "white_thighhighs白色过膝袜",
            enable: true,
          },
          {
            value: "torn_thighhighs",
            title: "torn_thighhighs损坏了的过膝袜",
            enable: true,
          },
          { value: "tabi", title: "tabi日式厚底短袜", enable: true },
          {
            value: "lace-trimmed legwear",
            title: "lace-trimmed legwear蕾丝镶边紧身裤",
            enable: true,
          },
          { value: "leg_garter", title: "leg_garter腿部花边环", enable: true },
          {
            value: "ankle_lace-up",
            title: "ankle_lace-up腿部系带",
            enable: false,
          },
          { value: "thigh strap", title: "thigh strap 大腿系带", enable: true },
          {
            value: "legwear under shorts",
            title: "legwear under shorts 短裤下的紧身裤",
            enable: true,
          },
        ],
      },
    ],
  },
  {
    title: "装饰",
    enable: true,
    max: 2,
    min: 0,
    list: [
      {
        enable: true,
        max: 2,
        min: 0,
        title: "",
        list: [
          { value: "halo", title: "halo光环", enable: true },
          {
            value: "mini_top_hat",
            title: "mini_top_hat迷你礼帽",
            enable: true,
          },
          { value: "beret", title: "beret贝雷帽", enable: true },
          { value: "hood", title: "hood兜帽", enable: true },
          { value: "nurse cap", title: "nurse cap 护士帽", enable: true },
          { value: "tiara", title: "tiara皇冠", enable: true },
          { value: "oni horns", title: "oni horns鬼角", enable: true },
          { value: "demon horns", title: "demon horns恶魔角", enable: true },
          { value: "hair ribbon", title: "hair ribbon 发带", enable: true },
          {
            value: "flower ribbon",
            title: "flower ribbon花丝带",
            enable: true,
          },
          { value: "hairband", title: "hairband发卡", enable: true },
          { value: "hairclip", title: "hairclip发夹", enable: true },
          { value: "hair_ribbon", title: "hair_ribbon发带", enable: true },
          { value: "hair_flower", title: "hair_flower发花", enable: true },
          { value: "hair_ornament", title: "hair_ornament头饰", enable: true },
          { value: "bowtie", title: "bowtie蝴蝶结", enable: true },
          { value: "hair_bow", title: "hair_bow蝴蝶结发饰", enable: true },
          {
            value: "maid_headdress",
            title: "maid_headdress女仆头饰",
            enable: true,
          },
          { value: "bow", title: "bow服装饰品/头部饰品", enable: true },
          { value: "hair ornament", title: "hair ornament发饰", enable: true },
          {
            value: "heart hair ornament",
            title: "heart hair ornament心形",
            enable: true,
          },
          {
            value: "bandaid hair ornament",
            title: "bandaid hair ornament创可贴",
            enable: true,
          },
          { value: "hair bun", title: "hair bun 发包", enable: true },
          {
            value: "cone hair bun",
            title: "cone hair bun 锥形发髻",
            enable: true,
          },
          { value: "double bun", title: "double bun双发髻", enable: true },
          {
            value: "semi-rimless eyewear",
            title: "semi-rimless eyewear半无框的眼镜",
            enable: true,
          },
          { value: "sunglasses", title: "sunglasses太阳镜", enable: true },
          { value: "goggles", title: "goggles风镜", enable: true },
          { value: "eyepatch", title: "eyepatch眼罩(独眼)", enable: true },
          {
            value: "black blindfold",
            title: "black blindfold黑色眼罩",
            enable: true,
          },
          { value: "headphones", title: "headphones耳机", enable: true },
          { value: "veil", title: "veil面纱", enable: true },
          { value: "mouth mask", title: "mouth mask口罩", enable: true },
          { value: "glasses", title: "glasses眼镜", enable: true },
          { value: "earrings", title: "earrings耳环", enable: true },
          { value: "jewelry", title: "jewelry首饰", enable: true },
          { value: "bell", title: "bell铃铛", enable: true },
          { value: "ribbon_choker", title: "ribbon_choker颈带", enable: true },
          {
            value: "black choker",
            title: "black choker 颈部饰品",
            enable: true,
          },
          { value: "necklace", title: "necklace项链", enable: true },
          {
            value: "headphones around neck",
            title: "headphones around neck耳机套脖子上",
            enable: true,
          },
          { value: "collar", title: "collar 项圈", enable: true },
          {
            value: "sailor_collar",
            title: "sailor_collar水手领",
            enable: true,
          },
          { value: "neckerchief", title: "neckerchief领巾", enable: true },
          { value: "necktie", title: "necktie 领带", enable: true },
          {
            value: "cross necklace",
            title: "cross necklace十字架",
            enable: true,
          },
          { value: "pendant", title: "pendant 吊坠", enable: true },
          { value: "jewelry", title: "jewelry 珠宝", enable: true },
          { value: "scarf", title: "scarf围巾", enable: true },
          { value: "armband", title: "armband臂章", enable: false },
          { value: "armlet", title: "armlet臂环", enable: false },
          { value: "arm strap", title: "arm strap 臂带", enable: false },
          {
            value: "elbow gloves",
            title: "elbow gloves 肘部手套",
            enable: true,
          },
          { value: "half gloves", title: "half gloves 露指手套", enable: true },
          {
            value: "fingerless_gloves",
            title: "fingerless_gloves手镯",
            enable: true,
          },
          { value: "gloves", title: "gloves手套", enable: false },
          {
            value: "fingerless gloves",
            title: "fingerless gloves 五指手套",
            enable: false,
          },
          { value: "chains", title: "chains锁链", enable: false },
          { value: "shackles", title: "shackles手链", enable: false },
          { value: "cuffs", title: "cuffs手铐", enable: false },
          { value: "handcuffs", title: "handcuffs手铐", enable: false },
          { value: "bracelet", title: "bracelet手镯", enable: true },
          { value: "wristwatch", title: "wristwatch手表", enable: true },
          { value: "wristband", title: "wristband腕带", enable: true },
          { value: "wrist_cuffs", title: "wrist_cuffs腕饰", enable: true },
          { value: "holding book", title: "holding book拿着书", enable: true },
          {
            value: "holding sword",
            title: "holding sword拿着剑",
            enable: false,
          },
          { value: "tennis racket", title: "tennis racket球拍", enable: true },
          { value: "cane", title: "cane手杖", enable: true },
          { value: "backpack", title: "backpack双肩包", enable: true },
          { value: "school bag", title: "school bag 书包", enable: true },
          { value: "satchel", title: "satchel肩背书包", enable: true },
          { value: "smartphone", title: "smartphone 手机", enable: true },
          { value: "bandaid", title: "bandaid创可贴", enable: false },
        ],
      },
    ],
  },
  {
    title: "R18",
    enable: true,
    max: 2,
    min: 2,
    list: [
      {
        enable: true,
        max: 20,
        min: 2,
        title: "",
        list: [
          { value: "tentacle", title: "tentacle触手", enable: true },
          { value: "hairjob", title: "hairjob发交", enable: true },
          { value: "oral/fellatio", title: "oral/fellatio口交", enable: true },
          { value: "deepthroat", title: "deepthroat深喉", enable: true },
          { value: "gokkun", title: "gokkun吃精", enable: true },
          { value: "gag", title: "gag口塞", enable: true },
          { value: "ballgag", title: "ballgag球塞", enable: true },
          { value: "bitgag", title: "bitgag棍塞", enable: true },
          { value: "ring_gag", title: "ring_gag扩口器", enable: true },
          { value: "cleave_gag", title: "cleave_gag用布勒住嘴", enable: true },
          { value: "panty_gag", title: "panty_gag用内裤塞口", enable: true },
          { value: "tapegag", title: "tapegag胶带封口", enable: true },
          { value: "facial", title: "facial颜射", enable: true },
          { value: "leash", title: "leash宠物链", enable: true },
          { value: "handjob", title: "handjob用手做", enable: true },
          { value: "groping", title: "groping摸索", enable: true },
          { value: "areolae", title: "areolae乳晕", enable: true },
          { value: "nipples", title: "nipples乳头", enable: true },
          {
            value: "puffy_nipples",
            title: "puffy_nipples大乳头",
            enable: false,
          },
          {
            value: "small_nipples",
            title: "small_nipples小乳头",
            enable: true,
          },
          { value: "nipple_pull", title: "nipple_pull啦乳头", enable: false },
          {
            value: "nipple_torture",
            title: "nipple_torture虐乳头",
            enable: false,
          },
          { value: "nipple_tweak", title: "nipple_tweak捏乳头", enable: true },
          {
            value: "nipple_piercing",
            title: "nipple_piercing乳头穿孔",
            enable: false,
          },
          { value: "breast_grab", title: "breast_grab摸乳", enable: true },
          {
            value: "lactation",
            title: "lactation哺乳（大范围）",
            enable: true,
          },
          {
            value: "breast_sucking/nipple_suck",
            title: "breast_sucking/nipple_suck吸乳（中）",
            enable: true,
          },
          {
            value: "breast_feeding",
            title: "breast_feeding喂奶(小)",
            enable: true,
          },
          { value: "paizuri", title: "paizuri乳交", enable: true },
          {
            value: "multiple_paizuri",
            title: "multiple_paizuri多P乳交",
            enable: true,
          },
          {
            value: "breast_smother",
            title: "breast_smother把头塞入胸",
            enable: true,
          },
          { value: "piercing", title: "piercing穿孔", enable: true },
          {
            value: "navel_piercing",
            title: "navel_piercing肚脐穿孔",
            enable: true,
          },
          { value: "thigh_sex", title: "thigh_sex腿交", enable: true },
          { value: "footjob", title: "footjob足交", enable: true },
          {
            value: "mound_of_venus",
            title: "mound_of_venus腹部三角带",
            enable: true,
          },
          { value: "wide_hips", title: "wide_hips宽盆骨", enable: true },
          { value: "masturbation", title: "masturbation自慰", enable: true },
          {
            value: "clothed_masturbation",
            title: "clothed_masturbation隔着衣服自慰",
            enable: true,
          },
          { value: "penis", title: "penis阳具/屌", enable: true },
          { value: "testicles", title: "testicles睾丸/蛋蛋", enable: true },
          { value: "ejaculation", title: "ejaculation射出", enable: true },
          { value: "cum", title: "cum射精", enable: true },
          { value: "cum_inside", title: "cum_inside内射", enable: true },
          {
            value: "cum_on_breast",
            title: "cum_on_breast射在胸上",
            enable: true,
          },
          {
            value: "cum_on_hair",
            title: "cum_on_hair射在头发上",
            enable: true,
          },
          {
            value: "cum_on_food",
            title: "cum_on_food射在食物上",
            enable: true,
          },
          { value: "tamakeri", title: "tamakeri蛋疼", enable: true },
          {
            value: "pussy/vaginal",
            title: "pussy/vaginal阴户（前者图片远大于后者）",
            enable: true,
          },
          { value: "pubic_hair", title: "pubic_hair阴毛", enable: true },
          {
            value: "shaved_pussy",
            title: "shaved_pussy剃过阴毛的（无毛B）",
            enable: true,
          },
          { value: "no_pussy", title: "no_pussy没逼的", enable: true },
          { value: "clitoris", title: "clitoris阴蒂", enable: true },
          { value: "fat_mons", title: "fat_mons肥逼", enable: true },
          {
            value: "cameltoe",
            title: "cameltoe骆驼脚趾逼（俗称馒头逼）",
            enable: true,
          },
          { value: "pussy_juice", title: "pussy_juice爱液", enable: true },
          {
            value: "female_ejaculation",
            title: "female_ejaculation潮吹",
            enable: true,
          },
          { value: "grinding", title: "grinding性器摩擦", enable: true },
          { value: "crotch_rub", title: "crotch_rub胯部摩擦", enable: true },
          { value: "facesitting", title: "facesitting坐在脸上", enable: true },
          { value: "cervix", title: "cervix子宫口", enable: true },
          { value: "cunnilingus", title: "cunnilingus舔阴", enable: true },
          { value: "insertion", title: "insertion插入物", enable: true },
          {
            value: "anal_insertion",
            title: "anal_insertion菊花插入物",
            enable: true,
          },
          {
            value: "fruit_insertion",
            title: "fruit_insertion用水果蔬菜",
            enable: true,
          },
          {
            value: "large_insertion",
            title: "large_insertion巨大插入",
            enable: true,
          },
          { value: "penetration", title: "penetration异物插入", enable: true },
          { value: "fisting", title: "fisting拳头插入", enable: true },
          { value: "fingering", title: "fingering手插入", enable: true },
          {
            value: "multiple_insertions",
            title: "multiple_insertions一穴多插",
            enable: true,
          },
          {
            value: "double_penetration",
            title: "double_penetration双穴同插",
            enable: true,
          },
          {
            value: "triple_penetration",
            title: "triple_penetration三穴同插",
            enable: true,
          },
          {
            value: "double_vaginal",
            title: "double_vaginal双重入穴",
            enable: true,
          },
          { value: "peeing", title: "peeing尿尿", enable: true },
          { value: "have_to_pee", title: "have_to_pee憋尿", enable: true },
          { value: "ass", title: "ass屁股", enable: true },
          { value: "huge_ass", title: "huge_ass大屁股", enable: true },
          {
            value: "spread_ass",
            title: "spread_ass用手张开屁股",
            enable: true,
          },
          { value: "buttjob", title: "buttjob臀交", enable: true },
          { value: "spanked", title: "spanked打屁股", enable: true },
          { value: "anus", title: "anus菊花", enable: true },
          { value: "anal", title: "anal爆菊", enable: true },
          { value: "double_anal", title: "double_anal双重爆菊", enable: true },
          {
            value: "anal_fingering",
            title: "anal_fingering手爆菊",
            enable: true,
          },
          { value: "anal_fisting", title: "anal_fisting拳爆菊", enable: true },
          { value: "anilingus", title: "anilingus肛吻", enable: true },
          { value: "enema", title: "enema灌肠", enable: true },
          {
            value: "stomach_bulge",
            title: "stomach_bulge肚子胀",
            enable: true,
          },
          {
            value: "x-ray/cross-section/internal_cumshot",
            title: "x-ray/cross-section/internal_cumshot透视人体内部",
            enable: true,
          },
          { value: "wakamezake", title: "wakamezake酒倒在阴部", enable: true },
          { value: "public", title: "public公共场所", enable: true },
          { value: "humiliation", title: "humiliation羞耻play", enable: true },
          { value: "bra_lift", title: "bra_lift胸罩拉到胸上方", enable: true },
          {
            value: "panties_around_one_leg",
            title: "panties_around_one_leg内裤挂在一条腿上",
            enable: true,
          },
          { value: "caught", title: "caught被发现", enable: true },
          { value: "walk-in", title: "walk-in进门被发现", enable: true },
          {
            value: "body_writing",
            title: "body_writing身上有字",
            enable: true,
          },
          { value: "tally", title: "tally在身上计数", enable: true },
          { value: "futanari", title: "futanari双性", enable: true },
          { value: "incest", title: "incest乱伦", enable: true },
          {
            value: "twincest",
            title: "twincest兄弟/姐妹/姐弟/兄妹",
            enable: true,
          },
          { value: "pegging", title: "pegging女性使用假屌", enable: true },
          { value: "femdom", title: "femdom女奸男（逆推）", enable: true },
          { value: "ganguro", title: "ganguro日本黑妹", enable: true },
          { value: "bestiality", title: "bestiality人兽", enable: true },
          { value: "gangbang", title: "gangbang轮奸", enable: true },
          { value: "hreesome", title: "hreesome3P", enable: true },
          {
            value: "group_sex/orgy/teamwork",
            title: "group_sex/orgy/teamwork群P（多男x一女/性交派队/多女x1男）",
            enable: true,
          },
          { value: "tribadism", title: "tribadism磨豆腐", enable: true },
          { value: "molestation", title: "molestation性骚扰", enable: true },
          { value: "voyeurism", title: "voyeurism窥阴癖", enable: true },
          {
            value: "exhibitionism",
            title: "exhibitionism裸露癖",
            enable: true,
          },
          { value: "rape", title: "rape强暴", enable: true },
          {
            value: "about_to_be_raped",
            title: "about_to_be_raped将要被强暴",
            enable: true,
          },
          { value: "sex", title: "sex性爱", enable: true },
          {
            value: "clothed_sex",
            title: "clothed_sex穿着衣服做爱",
            enable: true,
          },
          { value: "happy_sex", title: "happy_sex快乐做爱", enable: true },
          {
            value: "underwater_sex",
            title: "underwater_sex水中做爱",
            enable: true,
          },
          { value: "spitroast", title: "spitroast前后夹攻", enable: true },
          {
            value: "cock_in_thighhigh",
            title: "cock_in_thighhigh插在过膝袜里",
            enable: true,
          },
          { value: "69", title: "6969式", enable: true },
          { value: "doggystyle", title: "doggystyle狗爬式", enable: true },
          {
            value: "leg_lock/upright_straddle",
            title: "leg_lock/upright_straddle跨坐式",
            enable: true,
          },
          { value: "missionary", title: "missionary传教士体位", enable: true },
          { value: "girl_on_top", title: "girl_on_top女上体位", enable: true },
          {
            value: "cowgirl_position",
            title: "cowgirl_position女上正骑",
            enable: true,
          },
          {
            value: "reverse_cowgirl",
            title: "reverse_cowgirl女上反骑",
            enable: true,
          },
          { value: "virgin", title: "virgin处女/破瓜", enable: true },
          { value: "slave", title: "slave奴隶", enable: true },
          { value: "shibari", title: "shibari捆绑", enable: true },
          { value: "bondage", title: "bondage捆绑/奴役", enable: true },
          {
            value: "bdsm",
            title: "bdsm绑缚与调教/支配与臣服/施虐与受虐",
            enable: true,
          },
          {
            value: "pillory/stocks",
            title: "pillory/stocks枷锁",
            enable: true,
          },
          { value: "rope", title: "rope绳子", enable: true },
          { value: "bound_arms", title: "bound_arms手臂捆绑", enable: true },
          {
            value: "bound_wrists",
            title: "bound_wrists手腕捆绑",
            enable: true,
          },
          { value: "crotch_rope", title: "crotch_rope胯下捆绑", enable: true },
          { value: "hogtie", title: "hogtie曲膝捆绑", enable: true },
          { value: "frogtie", title: "frogtie青蛙捆绑", enable: true },
          { value: "suspension", title: "suspension悬空捆绑", enable: true },
          {
            value: "spreader_bar",
            title: "spreader_bar分腿捆绑",
            enable: true,
          },
          { value: "wooden_horse", title: "wooden_horse木马", enable: true },
          { value: "anal_beads", title: "anal_beads肛珠", enable: true },
          { value: "dildo", title: "dildo假屌", enable: true },
          { value: "cock_ring", title: "cock_ring屌环", enable: true },
          { value: "egg_vibrator", title: "egg_vibrator跳蛋", enable: true },
          {
            value: "artificial_vagina",
            title: "artificial_vagina人工阴道",
            enable: true,
          },
          {
            value: "hitachi_magic_wand",
            title: "hitachi_magic_wand按摩棒",
            enable: true,
          },
          { value: "dildo", title: "dildo人造阴茎", enable: true },
          { value: "double_dildo", title: "double_dildo双头龙", enable: true },
          { value: "vibrator", title: "vibrator带振动的自慰器", enable: true },
          {
            value: "vibrator_in_thighhighs",
            title: "vibrator_in_thighhighs震动开关在过膝袜里",
            enable: true,
          },
          { value: "nyotaimori", title: "nyotaimori女体盛", enable: true },
          { value: "vore", title: "vore吃人", enable: true },
          { value: "amputee", title: "amputee截肢", enable: true },
          {
            value: "transformation",
            title: "transformation肉体变形",
            enable: true,
          },
          {
            value: "mind_control",
            title: "mind_control思想操控",
            enable: true,
          },
          { value: "censored", title: "censored审核过的/有码", enable: true },
          {
            value: "uncensored",
            title: "uncensored未审核的/无码",
            enable: true,
          },
          { value: "asian", title: "asian亚洲", enable: true },
          {
            value: "faceless_male",
            title: "faceless_male无脸男",
            enable: true,
          },
          { value: "blood", title: "blood血", enable: true },
        ],
      },
    ],
  },
];
module.exports.prompts = prompts;
module.exports.promptsRdom = function promptsRdom(tags = prompts) {
  return tags
    .filter((f) => f.enable)
    .map((v) => {
      if (v.list) {
        let num = v.min >= v.max ? v.min : randomNum(v.max, v.min);
        let arr = [];
        let cache = [...v.list.filter((v) => v.enable)];
        for (let i = 0; i < num; i++) {
          arr.push(cache[randomNum(cache.length - 1, 0)]);
        }
        return promptsRdom(arr);
      } else if(v.value){
        return v.value;
      }
    }).filter(v=>v)
    .join(",");
};

function randomNum(max, min) {
  const num = Math.floor(Math.random() * (max - min + 1)) + min;
  return num;
}
