module.exports.prompts = [
  [999, "prompts"],
  [
    [3, "环境"],
    [
      [1, "朝朝暮暮"],
      "day",
      " dusk",
      " night",
      " in spring",
      " in summer",
      " in autumn",
      " in winter",
    ],
    [
      [1, "日月星辰"],
      "sun",
      " sunset",
      " moon",
      " full_moon",
      " stars",
      " cloudy",
      " rain",
      " in the rain",
      " rainy days",
    ],
    [
      [1, "天涯海角"],
      "sky",
      " sea",
      " mountain",
      " on a hill",
      " the top of the hill",
      " in a meadow",
      " plateau",
      " on a desert",
      " in hawaii",
      " cityscape",
      " landscape",
      " beautiful detailed sky",
      " beautiful detailed water",
      " on the beach",
      " on the ocean",
      " over the sea",
      " beautiful purple sunset at beach",
      " in the ocean",
      " against backlight at dusk",
      " golden hour lighting",
      " strong rim light",
      " intense shadows",
      " fireworks",
      " flower field",
      " underwater",
      " explosion",
      " in the cyberpunk city",
      " steam",
    ],
  ],
  [
    [2, "人物"],
    "girl",
    " 2girls",
    " 3girls",
    " solo",
    " multiple girls",
    " little girl",
    " loli",
    " kawaii",
    " adorable girl",
    " bishoujo",
    " gyaru",
    " sisters",
    " ojousama",
    " mature female",
    " mature",
    " female pervert",
    " milf",
    " harem",
  ],
  [
    [1, "角色"],
    "angel",
    " cheerleader",
    " chibi",
    " devil",
    " elf",
    " fairy",
    " female",
    " harem",
    " kemonomimi_mode",
    " loli",
    " magical_girl",
    " maid",
    " mermaid",
    " miko",
    " milf",
    " minigirl",
    " multiple_girls",
    " ninja",
    " nun",
    " nurse",
    " stewardess",
    " student",
    " vampire",
    " waitress",
    " witch",
    " yuri",
  ],
  [
    [3, "头发"],
    [
      [1, "发色"],
      "white hair",
      " blonde hair ",
      " silver hair",
      " grey hair ",
      " purple hair",
      " red hair",
      " yellow hair",
      " green hair",
      " blue hair",
      " black hair",
      " brown hair",
      " streaked hair",
      " grey gradient hair",
      " light brown hair",
      " two-tone hair",
      " multicolored hair",
    ],
    [
      [1, "辫子"],
      "high ponytail",
      " twintails",
      " braid",
      " braided ponytail ",
      " ponytail",
      " short_ponytail",
      " twin_braids",
    ],
    [
      [1, "发型"],
      "short hair",
      " medium hair",
      " long hair",
      " very long hair",
      " braided bangs",
      " swept bangs",
      " hair between eyes",
      " bob cut",
      " hime_cut",
      " crossed bangs",
      " bangs",
      " blunt bangs",
      " hair wings",
      " long bangs",
      " disheveled hair",
      " wavy hair",
      " curly_hair",
      " hair in takes",
      " scrunchie",
      " hair pink flowers",
      " ahoge",
      " antenna hair",
      " Side ponytail",
      " forehead",
      " drill hair",
      " hair bun",
      " double_bun",
      " messy_hair",
    ],
  ],
  [
    [1, "五官"],
    "light smile",
    " seductive smile",
    " grin",
    " laughing",
    " teeth ",
    " excited",
    " embarrassed ",
    " blush",
    " shy",
    " nose blush ",
    " expressionless",
    " expressionless eyes",
    " sleepy",
    " drunk",
    " tears",
    " crying with eyes open",
    " sad",
    " pout",
    " sigh",
    " wide eyed",
    " angry",
    " annoyed",
    " frown",
    " smirk",
    " serious",
    " jitome",
    " scowl",
    " crazy",
    " dark_persona",
    " smirk",
    " smug",
    " naughty_face",
    " one eye closed",
    " half-closed eyes",
    " nosebleed",
    " eyelid pull ",
    " tongue",
    " tongue out",
    " closed mouth",
    " open mouth",
    " lipstick",
    " fangs",
    " clenched teeth",
    " :3",
    " :p",
    " :q",
    " :t",
    " :d",
  ],
  [
    [1, "表情"],
    "food on face",
    " light blush",
    " facepaint",
    " makeup ",
    " cute face",
    " white colored eyelashes",
    " longeyelashes",
    " white eyebrows",
    " tsurime",
    " gradient_eyes",
    " beautiful detailed eyes",
    " tareme",
    " slit pupils ",
    " heterochromia ",
    " heterochromia blue red",
    " aqua eyes",
    " looking at viewer",
    " eyeball",
    " stare",
    " visible through hair",
    " looking to the side ",
    " constricted pupils",
    " symbol-shaped pupils ",
    " heart in eye",
    " heart-shaped pupils",
    " wink ",
    " mole under eye",
    " eyes closed",
    " no_nose",
    " fake animal ears",
    " animal ear fluff ",
    " animal_ears",
    " fox_ears",
    " bunny_ears",
    " cat_ears",
    " dog_ears",
    " mouse_ears",
    " hair ear",
    " pointy ears",
  ],
  [
    [2, "动作"],
    "head tilt",
    " turning around",
    " looking back",
    " looking down",
    " looking up",
    " smelling",
    " hand_to_mouth",
    " arm at side ",
    " arms behind head",
    " arms behind back ",
    " hand on own chest",
    " arms_crossed",
    " hand on hip",
    " hand on another's hip",
    " hand_on_hip",
    " hands_on_hips",
    " arms up",
    " hands up ",
    " stretch",
    " armpits",
    " leg hold",
    " grabbing",
    " holding",
    " fingersmile",
    " hair_pull",
    " hair scrunchie",
    " w ",
    " v",
    " peace symbol ",
    " thumbs_up",
    " middle_finger",
    " cat_pose",
    " finger_gun",
    " shushing",
    " waving",
    " salute",
    " spread_arms",
    " spread legs",
    " crossed_legs",
    " fetal_position",
    " leg_lift",
    " legs_up",
    " leaning forward",
    " fetal position",
    "  against wall",
    " on_stomach",
    " squatting",
    "  lying ",
    " sitting",
    " sitting on",
    " seiza",
    " wariza/w-sitting",
    " yokozuwari",
    " indian_style",
    " leg_hug",
    " walking",
    " running",
    " straddle",
    " straddling",
    " kneeling",
    " smoking",
    " arm_support",
    " caramelldansen",
    " princess_carry",
    " fighting_stance",
    " upside-down",
    " top-down_bottom-up",
    " bent_over",
    " arched_back",
    " back-to-back",
    " symmetrical_hand_pose",
    " eye_contact",
    " hug",
    " lap_pillow",
    " sleeping",
    " bathing",
    " mimikaki",
    " holding_hands",
  ],
  [
    [3, "服装"],
    "sailor collar",
    " hat",
    " shirt",
    " serafuku",
    " sailor suite",
    " sailor shirt",
    " shorts under skirt",
    " collared shirt ",
    " school uniform",
    " seifuku",
    " business_suit",
    " jacket",
    " suit ",
    " garreg mach monastery uniform",
    " revealing dress",
    " pink lucency full dress",
    " cleavage dress",
    " sleeveless dress",
    " whitedress",
    " wedding_dress",
    " Sailor dress",
    " sweater dress",
    " ribbed sweater",
    " sweater jacket",
    " dungarees",
    " brown cardigan ",
    " hoodie ",
    " robe",
    " cape",
    " cardigan",
    " apron",
    " gothic",
    " lolita_fashion",
    " gothic_lolita",
    " western",
    " tartan",
    " off_shoulder",
    " bare_shoulders",
    " barefoot",
    " bare_legs",
    " striped",
    " polka_dot",
    " frills",
    " lace",
    " buruma",
    " sportswear",
    " gym_uniform",
    " tank_top",
    " cropped jacket ",
    " black sports bra ",
    " crop top",
    " pajamas",
    " japanese_clothes",
    " obi",
    " mesh",
    " sleeveless shirt",
    " detached_sleeves",
    " white bloomers",
    " high - waist shorts",
    " pleated_skirt",
    " skirt",
    " miniskirt",
    " short shorts",
    " summer_dress",
    " bloomers",
    " shorts",
    " bike_shorts",
    " dolphin shorts",
    " belt",
    " bikini",
    " sling bikini",
    " bikini_top",
    "  bikini top only ",
    " side - tie bikini bottom",
    " side-tie_bikini",
    " friled bikini",
    "  bikini under clothes",
    " swimsuit",
    " school swimsuit",
    " one-piece swimsuit",
    " competition swimsuit",
    " Sukumizu",
  ],
  [
    [2, "鞋袜"],
    [
      [1, "鞋子"],
      "shoes ",
      " boots",
      " loafers",
      " high heels",
      " cross-laced_footwear",
      " mary_janes",
      " uwabaki",
      " slippers",
      " knee_boots",
    ],
    [
      [2, "袜子"],
      "pantyhose",
      " thighband pantyhose",
      " garter_belt",
      " garter straps",
      " socks",
      " striped_socks",
      " loose_socks",
      " legwear",
      " black leggings ",
      " leggings ",
      " fishnets",
      " fishnet_stockings",
      " fishnet_pantyhose",
      " kneehighs",
      " stockings",
      " thighhighs",
      " striped_thighhighs",
      " white_thighhighs",
      " torn_thighhighs",
      " tabi",
      " lace-trimmed legwear",
      " leg_garter",
      " ankle_lace-up",
      " thigh strap",
      " legwear under shorts",
    ],
  ],
  [
    [3, "装饰"],
    "halo",
    " mini_top_hat",
    " beret",
    " hood",
    " nurse cap",
    " tiara",
    " oni horns",
    " demon horns",
    " hair ribbon",
    " flower ribbon",
    " hairband",
    " hairclip",
    " hair_ribbon",
    " hair_flower",
    " hair_ornament",
    " bowtie",
    " hair_bow",
    " maid_headdress",
    " bow",
    " hair ornament",
    " heart hair ornament",
    " bandaid hair ornament",
    " hair bun",
    " cone hair bun",
    " double bun",
    " semi-rimless eyewear",
    " sunglasses",
    " goggles",
    " eyepatch",
    " black blindfold",
    " headphones",
    " veil",
    " mouth mask",
    " glasses",
    " earrings",
    " jewelry",
    " bell",
    " ribbon_choker",
    " black choker ",
    " necklace",
    " headphones around neck",
    " collar",
    " sailor_collar",
    " neckerchief",
    " necktie",
    " cross necklace",
    " pendant",
    " jewelry",
    " scarf",
    " armband",
    " armlet",
    " arm strap",
    " elbow gloves ",
    " half gloves ",
    " fingerless_gloves",
    " gloves",
    " fingerless gloves",
    " chains",
    " shackles",
    " cuffs",
    " handcuffs",
    " bracelet",
    " wristwatch",
    " wristband",
    " wrist_cuffs",
    " holding book",
    " holding sword",
    " tennis racket",
    " cane",
    " backpack",
    " school bag ",
    " satchel",
    " smartphone ",
    " bandaid",
  ],
];
